volumes:
  analyzer-models:

services:
  # Database service
  database:
    build:
      context: ./database
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'appdb'
      MARIADB_AUTO_UPGRADE: 'yes'
      MARIADB_DISABLE_UPGRADE_BACKUP: 'yes'
      DB_HOST: '127.0.0.1'
      DB_NAME: 'appdb'
      DB_USER: 'root'
      DB_PASS: ''
      TZ: ${TZ:-UTC}
    healthcheck:
      test: ['CMD-SHELL', 'test -f /var/tmp/ready.status']
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 60s
    volumes:
      - ${DB_DATA_DIR:?}:/var/lib/mysql:delegated
    expose:
      - '3306'

  # Webserver service
  webserver:
    build: ./webserver
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: 'database'
      DB_NAME: 'appdb'
      DB_USER: 'appuser'
      DB_PASS: ''
      SAMPLES_DATA_DIR: /data
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN:-}
      MAILGUN_FROM: ${MAILGUN_FROM:-}
      MAILGUN_APIKEY: ${MAILGUN_APIKEY:-}
      TZ: ${TZ:-UTC}
    volumes:
      - ${SAMPLES_DATA_DIR:?}:/data
    ports:
      - 80:80

  # Analyzer service
  analyzer:
    build:
      context: ./analyzer
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    stop_grace_period: 1m30s
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: 'database'
      DB_NAME: 'appdb'
      DB_USER: 'appuser'
      DB_PASS: ''
      SAMPLES_DATA_DIR: /data
      SAMPLES_TMP_DIR: /tmp_samples
      LOG_LEVEL: ${LOG_LEVEL:-}
      TZ: ${TZ:-UTC}
    volumes:
      - ${SAMPLES_DATA_DIR:?}:/data:ro
      - analyzer-models:/app/models
      - type: tmpfs
        target: /tmp_samples
        tmpfs:
          size: 4G
          mode: 01777
