<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?= empty($title) ? '' : "{$this->e($title)} - " ?><?= APP_NAME ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css" rel="stylesheet">
    <?= $this->section('styles') ?>
    <link href="/app.css?v=<?= urlencode(APP_VERSION) ?>" rel="stylesheet">
</head>
<body>
    <?php $this->insert('partials/topbar') ?>
    <main class="py-3" role="main">
        <?= $this->section('content') ?>
    </main>
    <?php $this->insert('partials/footer') ?>
    <script>window.Promise || document.write('<script src="/ie-polyfills.js"><\/script>')</script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js"></script>
    <?= $this->section('scripts') ?>
    <script src="/app.js?v=<?= urlencode(APP_VERSION) ?>"></script>
</body>
</html>
