<?php
use App\Utils\DB;
use App\Utils\Http;
use App\Utils\Session;
use App\Utils\Storage;
use ZipStream\ZipStream;

// Require authentication
Session::requireAuth();
$accountId = Session::getAccountId();

// Parse upload IDs from request
$uploadIds = ($_SERVER['REQUEST_METHOD'] === 'POST') ?
    explode(',', $_POST['samples'] ?? '') :
    [mb_substr(Http::getUri(), 10)];
$uploadIds = array_filter($uploadIds);
$uploadIds = array_slice($uploadIds, 0, max(RESULTS_ALLOWED_LIMITS));

// Get samples to export
$samples = DB::getAll(
    'SELECT u.id, u.name, u.label, u.uploaded_at, s.*
     FROM uploads u
     LEFT JOIN samples s ON s.digest=u.sample
     WHERE u.id IN (?a) AND u.account=?i
     ORDER BY s.acquired_at ASC',
    $uploadIds,
    $accountId
);

// Export CSV file
$format = $_POST['format'] ?? '';
if ($format === 'csv') {
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="export.csv"');

    // Send header
    echo "\xef\xbb\xbf"; // BOM for Excel
    $fields = ['name', 'upload_id', 'sample_id', 'target_id', 'position', 'acquired_at', 'calibrated_at', 'uploaded_at', 'label'];
    foreach (array_keys(RESULTS_MODELS) as $model) {
        $fields[] = "{$model}_prediction";
        $fields[] = "{$model}_confidence";
    }
    echo implode(';', $fields) . "\r\n";

    // Send sample rows
    foreach ($samples as $sample) {
        $row = [];
        $row[] = '"' . str_replace('"', '""', $sample['name']) . '"';
        $row[] = '"' . $sample['id'] . '"';
        $row[] = '"' . preg_replace('/(?:^.{4})?.{4}\K/', '-', bin2hex($sample['sample_id']), 4) . '"';
        $row[] = '"' . preg_replace('/(?:^.{4})?.{4}\K/', '-', bin2hex($sample['target_id']), 4) . '"';
        $row[] = '"' . $sample['position'] . '"';
        $row[] = gmdate('Y-m-d\\TH:i:s\\Z', strtotime($sample['acquired_at']));
        $row[] = gmdate('Y-m-d\\TH:i:s\\Z', strtotime($sample['calibrated_at']));
        $row[] = gmdate('Y-m-d\\TH:i:s\\Z', strtotime($sample['uploaded_at']));
        $row[] = RESULTS_ALLOWED_RIBOTYPES[$sample['label']] ?? '';
        foreach (array_keys(RESULTS_MODELS) as $model) {
            $confidence = array_key_exists("{$model}_confidence", $sample) ? $sample["{$model}_confidence"] : 1;
            $row[] = RESULTS_ALLOWED_RIBOTYPES[$sample["{$model}_result"]] ?? '';
            $row[] = ($sample["{$model}_result"] === null || $confidence === null) ? '' : round($confidence, 4);
        }
        echo implode(';', $row) . "\r\n";
    }

    return;
}

// Generate and send ZIP on-the-fly
ob_end_clean();
header('Content-Type: application/zip');
header('Content-Disposition: attachment; filename="export.zip"');
$dstZip = new ZipStream(sendHttpHeaders: false);
/** @var array<string,int> */
$counters = [];
foreach ($samples as $sample) {
    $srcPath = Storage::getPathToSample(bin2hex($sample['digest']));
    $srcZip = new ZipArchive();
    $srcZip->open($srcPath, ZipArchive::RDONLY);

    // Generate base path
    $basePath = Storage::sanitizePathPart($sample['name']) . "/0_{$sample['position']}";
    $counters[$basePath] = ($counters[$basePath] ?? 0) + 1;
    $basePath = "$basePath/{$counters[$basePath]}/1SLin";

    // Serve each file from sample
    $acquiredAt = DateTime::createFromFormat('U', strtotime($sample['acquired_at']));
    for ($i=0; $i<$srcZip->numFiles; $i++) {
        $itemPath = $srcZip->getNameIndex($i);
        $dstZip->addFileFromStream(
            fileName: "$basePath/$itemPath",
            stream: $srcZip->getStreamIndex($i),
            lastModificationDateTime: $acquiredAt
        );
    }

    // Add metadata file
    $metadata = [
        'name'          => $sample['name'],
        'upload_id'     => $sample['id'],
        'sample_id'     => preg_replace('/(?:^.{4})?.{4}\K/', '-', bin2hex($sample['sample_id']), 4),
        'target_id'     => preg_replace('/(?:^.{4})?.{4}\K/', '-', bin2hex($sample['target_id']), 4),
        'position'      => $sample['position'],
        'acquired_at'   => gmdate('Y-m-d\\TH:i:s\\Z', strtotime($sample['acquired_at'])),
        'calibrated_at' => gmdate('Y-m-d\\TH:i:s\\Z', strtotime($sample['calibrated_at'])),
        'uploaded_at'   => gmdate('Y-m-d\\TH:i:s\\Z', strtotime($sample['uploaded_at'])),
        'label'         => RESULTS_ALLOWED_RIBOTYPES[$sample['label']] ?? null,
    ];
    foreach (array_keys(RESULTS_MODELS) as $model) {
        $confidence = array_key_exists("{$model}_confidence", $sample) ? $sample["{$model}_confidence"] : 1;
        $metadata["{$model}_prediction"] = RESULTS_ALLOWED_RIBOTYPES[$sample["{$model}_result"]] ?? null;
        $metadata["{$model}_confidence"] = ($sample["{$model}_result"] === null || $confidence === null) ?
            null :
            round($confidence, 4);
    }
    $dstZip->addFile(
        fileName: "$basePath/autocdiff.json",
        data: json_encode($metadata, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT),
        lastModificationDateTime: $acquiredAt
    );

    $srcZip->close();
}
$dstZip->finish();
