<?php
use App\DB;
use App\Response;
use App\Session;

// Redirect if already logged in
if (Session::isAuthed()) {
    Response::redirect('/account');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $email = trim($_POST['email'] ?? '');
    $password = $_POST['password'] ?? '';

    // Validate credentials
    $account = DB::getRow('SELECT id, `password` FROM accounts WHERE email=?s', $email);
    if ($account !== null && password_verify($password, $account['password'])) {
        Session::login($account['id']);

        // Redirect to destination
        $redirectUri = parse_url($_GET['redirect'] ?? '/history');
        $redirectUri = $redirectUri['path'] . (isset($redirectUri['query']) ? "?{$redirectUri['query']}" : '');
        Response::redirect($redirectUri);
    }

    // Failed to authenticate
    $invalidCreds = true;
}
?>

<?php $this->layout('base', ['title' => 'Login']) ?>

<div class="container">
    <form class="session-form" method="post">
        <h2>Login</h2>
        <?php if (!empty($invalidCreds)) { ?>
            <div class="alert alert-danger" role="alert">Incorrect email address or password.</div>
        <?php } ?>
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" value="<?= $this->e($email ?? '') ?>" autocomplete="username" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" autocomplete="current-password" aria-describedby="password-help" required>
            <small id="password-help" class="form-text text-muted text-right">
                <a href="/reset-password">Forgot your password?</a>
            </small>
        </div>
        <button type="submit" class="btn btn-block btn-primary">Login</button>
        <div class="mt-4 pt-3 border-top small text-muted">Don't have an account? <a href="/signup">Sign Up</a></div>
    </form>
</div>
