<?php
use App\DB;
use App\Response;
use App\Session;

// Redirect if already logged in
if (Session::isAuthed()) {
    Response::redirect('/account');
}

// Validate token
$email = $_GET['email'] ?? '';
$token = $_GET['token'] ?? '';
$account = DB::getRow(
    'SELECT id, email
     FROM accounts
     WHERE email=?s
     AND password_reset_token=?s
     AND password_reset_sent_at>=?s',
    $email,
    $token,
    gmdate('Y-m-d H:i:s', time()-PASSWORD_RESET_LIFETIME)
);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($account === null) {
        Response::status(401);
    }

    // Validate new password
    $password = $_POST['password'] ?? '';
    $passwordConfirm = $_POST['password-confirm'] ?? '';
    $allValid = true;
    if (mb_strlen($password) < ACCOUNT_PASSWORD_MIN_LENGTH) {
        $passwordInvalid = sprintf('Must have ≥%d characters', ACCOUNT_PASSWORD_MIN_LENGTH);
        $allValid = false;
    }
    if ($password !== $passwordConfirm) {
        $passwordConfirmInvalid = 'Passwords do not match';
        $allValid = false;
    }

    // Update database
    if ($allValid) {
        DB::query(
            'UPDATE accounts
             SET `password`=?s, password_reset_token=NULL, updated_at=?s
             WHERE id=?i',
            password_hash($password, PASSWORD_BCRYPT, ['cost' => 12]),
            gmdate('Y-m-d H:i:s'),
            $account['id']
        );
    }
}
?>

<?php header('x-robots-tag: noindex,nofollow') ?>
<?php $this->layout('base', ['title' => 'Reset password']) ?>

<?php if (!empty($allValid)) { ?>
    <div class="container text-center py-5 my-5">
        <h1>Account password changed</h1>
        <p class="mt-3 mb-2">Your account password was successfully changed.</p>
        <p>You can now <a href="/login">login</a> with your new password.</p>
    </div>
<?php } elseif ($account === null) { ?>
    <div class="container text-center py-5 my-5">
        <h1>Invalid password reset link</h1>
        <p class="mt-3 mb-2">This link is invalid or has expired. Please request a new password reset link.</p>
    </div>
<?php } else { ?>
    <div class="container">
        <form class="session-form" method="post">
            <h2>Reset password</h2>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" value="<?= $this->e($account['email']) ?>" autocomplete="username" readonly>
            </div>
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <label for="password">New password</label>
                        <input type="password" class="form-control<?= empty($passwordInvalid) ? '' : ' is-invalid' ?>" id="password" name="password" autocomplete="new-password" aria-describedby="password-help" minlength="<?= ACCOUNT_PASSWORD_MIN_LENGTH ?>" required>
                        <?php if (empty($passwordInvalid)) { ?>
                            <small id="password-help" class="form-text text-muted">Use <?= ACCOUNT_PASSWORD_MIN_LENGTH ?> or more characters</small>
                        <?php } else { ?>
                            <div class="invalid-feedback"><?= $passwordInvalid ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="password-confirm">Confirm password</label>
                        <input type="password" class="form-control<?= empty($passwordConfirmInvalid) ? '' : ' is-invalid' ?>" id="password-confirm" name="password-confirm" autocomplete="new-password" aria-describedby="password-confirm-help" minlength="<?= ACCOUNT_PASSWORD_MIN_LENGTH ?>" required>
                        <?php if (empty($passwordConfirmInvalid)) { ?>
                            <small id="password-confirm-help" class="form-text text-muted">Repeat the new password</small>
                        <?php } else { ?>
                            <div class="invalid-feedback"><?= $passwordConfirmInvalid ?></div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-block btn-primary">Change password</button>
        </form>
    </div>
<?php } ?>
