<?php
use App\DB;
use App\Http;
use App\Mailgun;
use App\Response;
use App\Session;

// Redirect if already logged in
if (Session::isAuthed()) {
    Response::redirect('/account');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $now = time();
    $email = trim($_POST['email'] ?? '');
    $account = DB::getRow(
        'SELECT id, email, firstname
         FROM accounts
         WHERE email=?s
         AND (password_reset_sent_at IS NULL OR password_reset_sent_at<?s)',
        $email,
        gmdate('Y-m-d H:i:s', $now-PASSWORD_RESET_LIFETIME)
    );
    if ($account === null) {
        usleep(1000*300); // Wait 300ms to mitigate side-channel attacks
    } else {
        // Generate link
        $token = bin2hex(random_bytes(20));
        $link = Http::getBaseUrl() . '/reset-password-confirm?email=' . urlencode($account['email']) .
            '&token=' . urlencode($token);

        // Persist in database
        DB::query(
            'UPDATE accounts SET password_reset_token=?s, password_reset_sent_at=?s WHERE id=?i',
            $token,
            gmdate('Y-m-d H:i:s', $now),
            $account['id']
        );

        // Send link
        $subject = sprintf('Your password reset link for %s', APP_NAME);
        $message = sprintf(
            "Hello %s,\n\n" .
            "We received a password reset request for your account. DO IGNORE THIS MESSAGE IF IT WAS NOT YOU.\n\n" .
            "You can click this link to reset your password:\n" .
            "%s\n\n" .
            "Note the link will expire in %d hours.\n\n" .
            "Regards,\nThe %s Team",
            $account['firstname'],
            $link,
            floor(PASSWORD_RESET_LIFETIME / 3600),
            APP_NAME
        );
        Mailgun::sendEmail($account['email'], $subject, $message);
    }
    $sent = true;
}
?>

<?php $this->layout('base', ['title' => 'Reset password']) ?>

<div class="container">
    <form class="session-form" method="post">
        <h2>Reset password</h2>
        <?php if (empty($sent)) { ?>
            <div class="alert alert-info" role="alert">
                Enter your email address and we'll send you a link to reset your password.
            </div>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <button type="submit" class="btn btn-block btn-primary">Send reset link</button>
        <?php } else { ?>
            <div class="alert alert-success" role="alert">
                We sent a password reset link to your email address.
                Make sure to check the spam folder.
            </div>
        <?php } ?>
    </form>
</div>
