<footer class="border-top py-3 py-sm-4">
    <div class="container">
        <div class="row">
            <div class="col">
                <span class="mb-3 mb-md-0 text-muted">© <?= date('Y') ?> Company, Inc</span>
            </div>
            <ul class="col-auto nav justify-content-end list-unstyled d-flex">
                <li class="ml-3">
                    <a title="Twitter" href="#" target="_blank" class="text-muted"><i class="bi bi-twitter"></i></a>
                </li>
                <li class="ml-3">
                    <a title="Instagram" href="#" target="_blank" class="text-muted"><i class="bi bi-instagram"></i></a>
                </li>
                <li class="ml-3">
                    <a title="Facebook" href="#" target="_blank" class="text-muted"><i class="bi bi-facebook"></i></a>
                </li>
            </ul>
        </div>
    </div>
</footer>
