<footer class="border-top pb-5 pt-3 pt-sm-4">
    <div class="container">
        <div class="row">
            <div class="col-sm mb-4 mb-sm-0">
                <p class="h5 mb-1"><?= APP_NAME ?></p>
                <p class="small text-muted m-0">Automatic Clostridioides difficile Typing</p>
            </div>
            <div class="col-sm-auto d-flex">
                <a href="https://www.iisgm.com/" target="_blank" class="mr-4">
                    <img src="logo-iisgm.png" height="40" alt="Instituto de Investigación Sanitaria Gregorio Marañón">
                </a>
                <a href="https://www.uc3m.es/" target="_blank" class="">
                    <img src="logo-uc3m.png" height="40" alt="Universidad Carlos III de Madrid">
                </a>
            </div>
        </div>
    </div>
</footer>
